all:bubblesort 
	
bubblesort.o:bubblesort.c
	gcc -g -Wall -ansi -c -o bubblesort.o bubblesort.c

hexaPrint.o:hexaPrint.c
	gcc -g -Wall -ansi -c -o hexaPrint.o hexaPrint.c
	
.PHONY: clean

clean:
	rm -f *.o bubblesort.o hexaPrint.o
